### ISSUE TITLE
Samples how to use the SDK 

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/python-viptela#41]
Can you add information and sample how to use the SDK methods in python code.
How initialize connection etc?

**Comment by stevenca** [comment]
Working on documentation and sample code for this in time for Cisco Live.

**Comment by stevenca** [comment]
Can you list a few examples that you would like to see?

**Comment by stevenca** [comment]
Samples Added.  Using the SDK will also be covered when DevNetDays actually airs.
