### ISSUE TITLE
export attachment fails - just last variable was exported - even more exists in template and box is attached to it. 

### ISSUE THREAD

**Issue by pm7625** [CiscoDevNet/python-viptela#68]
Hello

When I tried export attachments from the box, all the time it exported just last variable, i tried to change variables, number of variables, but all the time just last one was shown and exported. 
Those previous are under "null" section. 

vManage code 20.1.1
Will try it again on production vManage where I have 19.2.2

Example of such attachments
{
"vmanage_attachments": [
{
"host_name": "vEdge1kupperOld",
"device_type": "vedge",
"uuid": "11OG637181517",
"system_ip": "198.18.6.2",
"site_id": "11000000",
"template": "vEdge1k_upper_template",
"variables": {
"null": "vEdge1kupperOld"
}
}
]
}

I have CLI templates and for sure more variables, in this example I had 3 variables.

**Comment by suchandanreddy** [comment]
@pm7625 I have seen similar issue #66 with the variables being `null` and storing only last variable. I have fixed it in the PR #67 but to confirm that would fix your issue too, can you please share more details on the template you are using, is it CLI template or Device Feature template ?

**Comment by suchandanreddy** [comment]
issues are fixed through PR #77 and we have fix integrated to master
